# Generated by Django 6.0.4 on 2026-04-09 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsavel',
            name='nome',
            field=models.CharField(max_length=150),
        ),
    ]
